import { CheckCircle2, CreditCard, Landmark, LoaderCircle, Smartphone } from "lucide-react";
import { useEffect, useState } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { Button } from "../components/ui/Button";
import { ErrorState } from "../components/ui/ErrorState";
import { apiClient, request } from "../api/client";
import { customerService } from "../services/customerService";
import { paymentService } from "../services/paymentService";

type PaymentMethod = "upi" | "net_banking" | "card";
const methods: { id: PaymentMethod; label: string; description: string; icon: typeof Smartphone }[] = [
  { id: "upi", label: "UPI / Google Pay", description: "Pay securely with your preferred UPI app", icon: Smartphone },
  { id: "net_banking", label: "Net Banking", description: "Continue with your bank", icon: Landmark },
  { id: "card", label: "Card", description: "Credit and debit cards accepted", icon: CreditCard }
];

export function MockPaymentPage() {
  const navigate = useNavigate(); const [params] = useSearchParams(); const bookingId = params.get("booking_id");
  const [booking, setBooking] = useState<Record<string, any> | null>(null); const [method, setMethod] = useState<PaymentMethod>("upi"); const [busy, setBusy] = useState(false); const [paid, setPaid] = useState<{ reference?: string; amount_cents?: number } | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { if (!bookingId) return; void Promise.all([customerService.getBooking(bookingId), paymentService.get(bookingId)]).then(([loaded, payment]) => { setBooking(loaded); if (payment?.status === "succeeded") setPaid({ reference: payment.stripe_payment_intent_id ?? undefined, amount_cents: payment.amount_cents }); }).catch((err) => setError(err instanceof Error ? err.message : "Unable to load booking.")); }, [bookingId]);
  useEffect(() => { if (!paid || !bookingId) return; const timer = window.setTimeout(() => navigate(`/booking/tracking?booking_id=${bookingId}`, { replace: true }), 1800); return () => window.clearTimeout(timer); }, [bookingId, navigate, paid]);
  async function pay() { if (!bookingId) return; setBusy(true); setError(null); try { const result = await request<{ reference?: string; amount_cents?: number }>(apiClient.post(`/payments/bookings/${bookingId}/mock-pay`, { payment_method: method, idempotency_key: `presentation-${bookingId}` })); setPaid(result); } catch (err) { setError(err instanceof Error ? err.message : "Payment could not be completed."); } finally { setBusy(false); } }
  if (!bookingId) return <ErrorState title="Booking reference missing" message="Return to the booking review and try again." />;
  if (paid) return <section className="mx-auto max-w-xl rounded-lg border border-slab-border bg-white p-8 text-center shadow-soft"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-slab-yellow"><CheckCircle2 size={34} /></div><h1 className="mt-5 text-3xl font-black text-slab-ink">{(paid.amount_cents || 0) === 0 ? "Emergency booking confirmed" : "Payment successful"}</h1><p className="mt-3 text-slab-muted">{(paid.amount_cents || 0) === 0 ? "SLAB Emergency Booking Fee is ₹0. Provider matching is now in progress." : "Your SLAB platform fee has been verified. Provider matching is now in progress."}</p><p className="mt-5 font-bold text-slab-ink">Reference: {paid.reference}</p><p className="mt-1 text-slab-muted">Amount paid to SLAB: ₹{((paid.amount_cents || 0) / 100).toLocaleString("en-IN")}</p><p className="mt-5 flex items-center justify-center gap-2 text-sm font-semibold text-slab-muted"><LoaderCircle className="animate-spin" size={16} /> Opening live tracking...</p></section>;
  const snapshot = booking?.pricing_snapshot || {}; const fee = Number(snapshot.platform_fee || 0);
  if (booking && fee === 0 && snapshot.is_emergency) return <section className="mx-auto max-w-xl space-y-6"><div><p className="text-sm font-bold uppercase text-slab-primaryStrong">Emergency booking</p><h1 className="mt-2 text-3xl font-black text-slab-ink">No SLAB booking fee</h1><p className="mt-2 text-slab-muted">SLAB Emergency Booking Fee is ₹0. Service and travel charges remain separate with the provider.</p></div>{error ? <ErrorState title="Emergency confirmation failed" message={error} /> : null}<section className="rounded-lg border border-slab-border bg-white p-6 shadow-soft"><p className="font-bold text-slab-ink">Booking {bookingId.slice(0, 8)}</p><p className="mt-2 text-sm text-slab-muted">{String(booking.status || "confirmed").replace(/_/g, " ")} · SLAB Emergency Booking Fee ₹0</p><Button className="mt-6 w-full" type="button" onClick={() => void pay()} disabled={busy}>{busy ? <><LoaderCircle className="animate-spin" size={16} /> Confirming emergency request...</> : "Continue to live tracking"}</Button></section></section>;
  return <section className="mx-auto max-w-xl space-y-6"><div><p className="text-sm font-bold uppercase text-slab-primaryStrong">Secure payment</p><h1 className="mt-2 text-3xl font-black text-slab-ink">Pay the SLAB platform fee</h1><p className="mt-2 text-slab-muted">Choose a payment method to confirm this booking and start provider matching.</p></div>{error ? <ErrorState title="Payment failed" message={error} /> : null}<section className="rounded-lg border border-slab-border bg-white p-6 shadow-soft"><div className="flex items-center gap-3 border-b border-slab-border pb-5"><CreditCard className="text-slab-primaryStrong" /><div><p className="font-bold text-slab-ink">Booking {bookingId.slice(0, 8)}</p><p className="text-sm text-slab-muted">{String(booking?.status || "payment_pending").replace(/_/g, " ")} · Platform fee ₹{fee.toLocaleString("en-IN")}</p></div></div><div className="mt-5 space-y-3">{methods.map((option) => { const Icon = option.icon; return <button key={option.id} type="button" onClick={() => setMethod(option.id)} className={`flex w-full items-center gap-4 rounded-md border p-4 text-left ${method === option.id ? "border-slab-primaryStrong bg-yellow-50" : "border-slab-border hover:bg-slate-50"}`}><Icon className="text-slab-primaryStrong" size={22} /><span><span className="block font-bold text-slab-ink">{option.label}</span><span className="mt-1 block text-sm text-slab-muted">{option.description}</span></span></button>; })}</div><Button className="mt-6 w-full" type="button" onClick={() => void pay()} disabled={busy || !booking}>{busy ? <><LoaderCircle className="animate-spin" size={16} /> Processing payment...</> : `Pay ₹${fee.toLocaleString("en-IN")}`}</Button></section></section>;
}
